FROM tomcat
RUN apt update
RUN apt install maven -y
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello
WORKDIR /usr/local/tomcat/boxfuse-sample-java-war-hello/
RUN ls -la
RUN mvn package
RUN cp target/hello-1.0.war /usr/local/tomcat/webapps
